config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'pages/home', to: 'pages#home'

  get 'pages/about', to: 'pages#about'

  get 'pages/resources', to: 'pages#resources'

  get 'pages/contact', to: 'pages#contact'

  get 'pages/admission', to: 'pages#admission'
  
  get 'pages/kelly', to: 'pages#kelly'

  get 'pages/dawn', to: 'pages#dawn'
  
  get 'pages/doreen', to: 'pages#doreen'

  get 'pages/christine', to: 'pages#christine'
  
  get 'pages/test', to: 'pages#test'


  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def resources
  end

  def contact
  end

  def admission
  end

  def kelly
  end

  def dawn
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inspiringminds</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render "shared/nav" %>
    <%= render "shared/footer" %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">
            <div><%= render 'shared/kelly' %></div>
        </div>
        <div class="col-lg-3">
            <div><%= render 'shared/dawn' %></div>
        </div>
        <div class="col-lg-3">
            <div><%= render 'shared/doreen' %></div>
        </div>
        <div class="col-lg-3">
            <div><%= render 'shared/christine' %></div>
        </div>
    </div>
</div>

app/views/pages/admission.html.erb
<div class="card contact">
  <h1 class="title">Admission</h1>
  <p class="title"><b>Reviewing Records:</b></p>
  <p>Sometimes you’ve had your school do all the testing and you still don’t understand what you should do now.  We are happy to meet with you and go over what the results mean, what to look for, and help you create an action plan for your child either with something as simple as modifications in the classroom, or bigger accommodations you may need.  We can gather information from these reports on whether enough testing has been done on your child or whether you need to go back to your school and request more.  The best part about this is testing has been done already and we are here to offer services of advice.</p>
  <p class="title"><b>Characteristics Profile Assessment:</b></p>  
  <p>You may be wondering if we are a fit for what you are looking for. We want to make sure we have the services you need.  Feel free to contact us and schedule a 45 minute, inexpensive evaluation to see if the multisensory curriculum we provide is a match for your child.  This evaluation includes a Dyslexia Determination Test, Spelling assessment, writing assessment, sight word recognition, reading rate, fluency, and comprehension evaluation.</p>
  <p class="title"><b>Dyslexia Screening:</b></p> 
  <p>A dyslexia screening is a more in depth evaluation and assessment to help parents that are struggling to receive the services their child needs in their school.  This screening includes looking specifically at the specific areas that schools look at for learning disabilities.  This also includes Inspiring Minds being a students advocate in an IEP meeting.</p>

  <p class="title"><b>Feel free to contact us with any questions you may have.</b></p>
</div>

app/views/pages/contact.html.erb
<div class="card contact1">
  <h1>Contact</h1>
  <p>Kelly Tate, Director of Inspiring Minds</p> 
  <p>Phone: (801) 369-6639</p>
  <p>Email: kellylortate@gmail.com</p>
</div>

app/views/pages/dawn.html.erb
<h1>Dawn Ella Tate, Dyslexia Tutor</h1>

<p>
  Dawn obtained an Associates Degree with an emphasis in Education from Brigham Young University Idaho, followed by a Baccalaureate Degree in General Family Life and Social Sciences from Brigham Young University, Provo.  Dawn is currently trained in The Orton Gillingham Approach.   Dawn has been working with students with dyslexia for four years.   Dawn loves education stating,  “There is nothing more beautiful than watching one overcome and conquer their challenges.  She portrays this ambition to her students thus building self-confidence and learning.
</p>

app/views/pages/home.html.erb
<div class='container-fluid'>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "img1.png", alt: "home-image1", class: 'home-image' %> 
      </div>
      <div class="carousel-item">
        <%= image_tag "img2.png", alt: "home-image2", class: 'home-image' %>
      </div>
      <div class="carousel-item">
        <%= image_tag "img3.png", alt: "home-image3", class: 'home-image' %>
      </div>
      <div class="carousel-item">
        <%= image_tag "img4.png", alt: "home-image4", class: 'home-image' %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
 

app/views/pages/kelly.html.erb
<div class="kelly-card">
  <div class="card">
    <div class="card-block">
      <h4 class="card-title">Kelly Tate, Director of Inspiring Minds and Dyslexia Therapist</h4>
      <p class="card-text">Kelly Tate is a Certified Academic Language Therapist,CALT) and is qualified to treat children and adults diagnosed with written-language learning disabilities. As an Academic Language Therapist, she also holds a masters degree in Educational Administration and a  Baccalaureate Degree in special education and k-12 grade education and has completed extensive post-graduate education from The Scottish Rite Learning Center inWest Texas in Alphabetic Phonics and Take Flight curriculum. Both of these programs are Orton Gillingham based programs designed and recognized by The Scottish Rite Hospital and The National Reading Panel as proven methods to overcoming dyslexia.   Mrs. Tate has taught in the public education system for a number of years and has taught students with learning disabilities (dyslexia) for eleven years.  She has been trained in Alphabetic Phonics and The Take Flight Curriculum (both are Orton Gillinghas programs that are recognized by The International Multisensory Structured Language Education Council (imslec.org), The National Reading Panel, and the Scottish Rite Hospital as well as other organizations.  She taught spanish as a second language as well.</p>
      <p class="card-text"><small class="text-muted"></small></p>
    </div>
  </div>
</div>
    
  

app/views/pages/resources.html.erb
<div class="card contact">
  <h1 class="title">Resources</h1>
  <p class="title"><b>RECOMENDED BOOKS:</b></p> 
  <div class="body">
  <p>-The Everything Parent’s Guide to Children with Dyslexia</p>
  <p>-Overcoming Dyslexia: A New and Complete Science-Based Program for Reading Problems at Any Level-Sally Schawitz, M.D.</p>
  <p>-How to Reach and Teach Children and Teens with Dyslexia: A Parent and Teacher Guide to Helping Students of All Ages Acaemically, Socially, and Emotionally (J-B Ed: Reach and Teach) by Cynthia M. Stowe M.Ed.</p>
  <p>-The Dyslexia Checklist: A Practical Reference for Parents and Tea (J.B. Ed: Check list) by Sandra F. Rief M.A. and Judith Stern M.A.</p>
  <p>-The Secret Life of the Dyslexic Child: How she thinks. How he feels. How they can succeed-Robert Frank, PhD</p>
  <p>-Dyslexia and Literacy: Theory and Practice (Open University Set Book) by Gavin Reid and Janice Wearmouth</p>
  <p>-What is Dyslexia?: A Book Explaining Dyslexia for Kids and Adults to Use Together-Alan M. Hultquist</p> 
  <p>-Dyslexia My Life by Girard J. Sagmiller</p>
  <p>-Dyslexia and ADHD: The Miracle Cure by Wynford Dore</p>
  <p>-Overcoming Dyslexia for Dummies-Tracey Wood</p>
  <p>-The International Book of Dyslexia: A Guide to Practice and Resources by Ian Smythe, John Everatt, and Robin Salter</p>
  <p>-The Gift of Dyslexia, Revised and Expanded: Why some of the Smartest People Can’t read…and How They Can Learn-Ronald D. Davis and Eldon M. Braun</p>
  <p class="title"><b>BOOKS FOR ADOLESENCE AND YOUTH:</b></p>
  <p>-JOSH: A Boy With Dyslexia by Caroline Janover</p>
  <p>-Life In a Jar-Stephen Sutton</p>
  <p>-My Name is Brain Brian-Jeanne Betancourt</p>
  <p>-My Friend Has Dyslexia (Friends with Disabilities) by Amanda Doering Tourville and Kristin Sorra</p>
  <p>-The Alphabet War: A Story about Dyslexia by Diane Burton Robb and Gail Piazza</p>
  <p>-It’s Called Dyslexia (Live and Learn Series)-Jennifer Moore-Mallinos</p>
  <p>-I Have Dyslexia.  What Does That Mean?-Shelley Ball-Dannenberg and Delaney Dannenberg</p>
  <p>-Taking Dyslexia to School (Special Kids in School) by Karen Schader and Tom Dineen</p>
  </div>
</div>

app/views/pages/sarah.html.erb
<div class="kelly-card">
  <div class="card">
    <div class="card-block">
      <h4 class="card-title">Sarah Adams, Dyslexia Tutor</h4>
      <p class="card-text"><p>Dawn obtained an Associates Degree with an emphasis in Education from Brigham Young University Idaho, followed by a Baccalaureate Degree in General Family Life and Social Sciences from Brigham Young University, Provo.  Dawn is currently trained in The Orton Gillingham Approach.   Dawn has been working with students with dyslexia for four years.   Dawn loves education stating,  “There is nothing more beautiful than watching one overcome and conquer their challenges.  She portrays this ambition to her students thus building self-confidence and learning.</p>
      <p class="card-text"><small class="text-muted"></small></p>
    </div>
  </div>
</div>

app/views/pages/test.html.erb
<div class="google-form">
  <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeHYJReKJ88vl9lk3VcL8sMBwmDRxB4XotuJkFD9paQOslvxQ/viewform?embedded=true" width="1000" height="6000" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</div>

app/views/pages/zuri.html.erb
<div class="kelly-card">
  <div class="card">
    <div class="card-block">
      <h4 class="card-title">Zuri Lorscheider, Dyslexia Tutor</h4>
      <p class="card-text"><p>Dawn obtained an Associates Degree with an emphasis in Education from Brigham Young University Idaho, followed by a Baccalaureate Degree in General Family Life and Social Sciences from Brigham Young University, Provo.  Dawn is currently trained in The Orton Gillingham Approach.   Dawn has been working with students with dyslexia for four years.   Dawn loves education stating,  “There is nothing more beautiful than watching one overcome and conquer their challenges.  She portrays this ambition to her students thus building self-confidence and learning.</p>
      <p class="card-text"><small class="text-muted"></small></p>
    </div>
  </div>
</div>

app/views/shared/_background.html.erb
<!-- <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">

          <%= video_tag(
                'Play.mp4', 
                id: 'background',
                autoplay: true,
                loop: true,
                muted: true,
                poster: 'Play.jpg'
            )
            %>
        </div>
    </div>
</div> -->

app/views/shared/_christine.html.erb
<div class="card testimonial-card">
  <div class="avatar mx-auto white"><img src="https://mdbootstrap.com/img/Photos/Avatars/img%20%2810%29.jpg" class="rounded-circle">
  </div>
    <div class="card-body">
      <h4 class="card-title"><p>Christine Craddock</p> <p>Dyslexia Tutor</p></h4>
      <hr>
        <%= link_to "Meet Christine ", pages_christine_path, class: "btn btn-lg btn-primary" %></p>
    </div>
</div>

app/views/shared/_dawn.html.erb
<div class="card testimonial-card">
  <div class="avatar mx-auto white"><img src="https://mdbootstrap.com/img/Photos/Avatars/img%20%2810%29.jpg" class="rounded-circle">
  </div>
    <div class="card-body">
      <h4 class="card-title"><p>Dawn Ella Tate</p> <p>Dyslexia Tutor</p></h4>
      <hr>
        <%= link_to "Meet dawn", pages_dawn_path, class: "btn btn-lg btn-primary" %></p>
    </div>
</div>

app/views/shared/_doreen.html.erb
<div class="card testimonial-card">
  <div class="avatar mx-auto white"><img src="https://mdbootstrap.com/img/Photos/Avatars/img%20%2810%29.jpg" class="rounded-circle">
  </div>
    <div class="card-body">
      <h4 class="card-title"><p>Doreen Hutchinson</p> <p>Dyslexia Tutor</p></h4>
      <hr>
        <%= link_to "Meet Doreen", pages_doreen_path, class: "btn btn-lg btn-primary" %></p>
    </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
    <div class="container-fluid">
      <div class="footer-content">
        <ul class="footer-block">
        <ul>Website created by Brett Lorscheider</ul>
        <ul><%= link_to "www.brettlorscheider.com", "http://www.brettlorscheider.com", :target => "_blank" %></ul>
        <ul><a href="mailto:brettlorsch@gmail.com">Email Me</a></ul>
        </ul>
      </div>
    </div>
  </div>

app/views/shared/_kelly.html.erb
<div class="card testimonial-card">
  <div class="avatar mx-auto white"><img src="https://mdbootstrap.com/img/Photos/Avatars/img%20%2810%29.jpg" class="rounded-circle">
  </div>
    <div class="card-body">
      <h4 class="card-title"><p>Kelly Tate</p> <p>Director</p></h4>
      <hr>
        <%= link_to "Meet Kelly", pages_kelly_path, class: "btn btn-lg btn-primary" %></p>
    </div>
</div>

app/views/shared/_nav.html.erb
<div class="header">
  <div class="container-fluid">
    <div class='logo'>
        <%= image_tag "logo.png", width: 350, alt: "logo", class: 'logo' %>
      </div>
    <div class='nav-links main-menu'>
      <%= link_to "Home", root_path %>
      <%= link_to "About", pages_about_path %>
      <%= link_to "Contact", pages_contact_path %>
      <%= link_to "Admission", pages_admission_path %>
      <%= link_to "Resources", pages_resources_path %>
      <%= link_to "Testing", pages_test_path %>
      <% if current_user %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Register", new_user_registration_path %>
        <%= link_to "Login", new_user_session_path %>
      <% end %>

    </div>
  </div>
</div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/shared/_sarah.html.erb
<div class="card testimonial-card">
  <div class="avatar mx-auto white"><img src="https://mdbootstrap.com/img/Photos/Avatars/img%20%2810%29.jpg" class="rounded-circle">
  </div>
    <div class="card-body">
      <h4 class="card-title"><p>Sarah Adams</p> <p>Dyslexia Tutor</p></h4>
      <hr>
        <%= link_to "Meet Sarah", pages_dawn_path, class: "btn btn-lg btn-primary" %></p>
    </div>
</div>

app/views/shared/_zuri.html.erb
<div class="card testimonial-card">
  <div class="avatar mx-auto white"><img src="https://mdbootstrap.com/img/Photos/Avatars/img%20%2810%29.jpg" class="rounded-circle">
  </div>
    <div class="card-body">
      <h4 class="card-title"><p>Zuri Lorscheider</p> <p>Dyslexia Tutor</p></h4>
      <hr>
        <%= link_to "Meet Zuri", pages_dawn_path, class: "btn btn-lg btn-primary" %></p>
    </div>
</div>